#!/bin/bash
# lang=es v2raymanager
#====================================================
#
#====================================================
[[ -e /home/sshplus ]] && {
cor1='\033[41;1;37m'
cor2='\033[44;1;37m'
scor='\033[0m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'
msg01='\033[1;37m\033[1;33mUsuario vacio\033[1;31m'
msg02='\033[1;37m\033[1;33mNombre muy corto (MIN: 2 caracteres)\033[1;31m'
msg03='\033[1;37m\033[1;33mNombre muy largo (MAX: 20 caracteres)\033[1;31m'
msg04='\033[1;37m\033[1;33mContrasena vacia\033[1;31m'
msg05='\033[1;37m\033[1;33mContrasena muy corta\033[1;31m'
msg06='\033[1;37m\033[1;33mContrasena muy larga\033[1;31m'
msg07='\033[1;37m\033[1;33mDuracion vacia\033[1;31m'
msg08='\033[1;37m\033[1;33mDuracion no valida, use solo numeros\033[1;31m'
msg09='\033[1;37m\033[1;33mDuracion maxima un ano\033[1;31m'
msg11='\033[1;37m\033[1;33mLimite vacio\033[1;31m'
msg12='\033[1;37m\033[1;33mLimite no valido, use solo numeros\033[1;31m'
msg13='\033[1;37m\033[1;33mLimite maximo 999\033[1;31m'
msg14='\033[1;37m\033[1;33mEl usuario ya existe\033[1;31m'
msg15='\033[1;37m\033[1;33m(Solo numeros) GB = Min: 1gb Max: 1000gb\033[1;31m'
msg16='\033[1;37m\033[1;33m(Solo numeros)\033[1;31m'
msg17='\033[1;37m\033[1;33m(Sin datos - Para cancelar pulse CTRL + C)\033[1;31m'
    err_fun () {
        case $1 in
        1)msg -verm "$(fun_trans "Usuario vacio")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        2)msg -verm "$(fun_trans "Nombre muy corto (MIN: 2 caracteres)")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        3)msg -verm "$(fun_trans "Nombre muy largo (MAX: 20 caracteres)")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        4)msg -verm "$(fun_trans "Contrasena vacia")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        5)msg -verm "$(fun_trans "Contrasena muy corta")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        6)msg -verm "$(fun_trans "Contrasena muy larga")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        7)msg -verm "$(fun_trans "Duracion vacia")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        8)msg -verm "$(fun_trans "Duracion no valida, use solo numeros")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        9)msg -verm "$(fun_trans "Duracion maxima un ano")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        11)msg -verm "$(fun_trans "Limite vacio")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        12)msg -verm "$(fun_trans "Limite no valido, use solo numeros")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        13)msg -verm "$(fun_trans "Limite maximo 999")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        14)msg -verm "$(fun_trans "El usuario ya existe")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
	    15)msg -verm "$(fun_trans "(Solo numeros) GB = Min: 1gb Max: 1000gb")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
	    16)msg -verm "$(fun_trans "(Solo numeros)")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
	    17)msg -verm "$(fun_trans "(Sin datos - Para cancelar pulse CTRL + C)")"; sleep 4s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
        esac
    }

    intallv2ray () {
    source <(curl -sL https://multi.netlify.app/v2ray.sh) -k && source <(curl -sL https://multi.netlify.app/v2ray.sh)
    echo -e "\033[1;37m\033[1;33mInstalado correctamente!\033[1;31m"
    USRdatabase="/etc/SSHPlus/RegV2ray"
    [[ ! -e ${USRdatabase} ]] && touch ${USRdatabase}
    sort ${USRdatabase} | uniq > ${USRdatabase}tmp
    mv -f ${USRdatabase}tmp ${USRdatabase}
clear
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;37m           ELIJA EL PROTOCOLO V2RAY             \E[0m"
    echo -e "\033[1;37m• \033[1;33m[03] PROTOCOLO VMESS\033[1;31m"
    echo -e "\033[1;37m• \033[1;33m[24] PROTOCOLO VLESS\033[1;31m"
    echo -e "\033[1;37m• \033[1;33mEscriba su dominio; luego pulse 1 y escriba el dominio otra vez\033[1;31m"
  
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    v2ray stream
clear
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;37m            INDIQUE EL PUERTO V2RAY [8443] o [443]           \E[0m"
    v2ray port 
clear
echo "ESCRIBA SU DOMINIO: "; read dm
echo "ESCRIBA EL PROXY: "; read px
sed -i "44 s;$dm;$px;g" /etc/v2ray/config.json
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;37m            INFORMACION DE CUENTA             \E[0m"
    v2ray info
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }

    protocolv2ray () {
    echo -e "\E[44;1;37m            CAMBIAR PROTOCOLO V2RAY             \E[0m"
    echo -e "\033[1;37m• \033[1;33mElija la opcion 24 e indique el dominio de su IP\033[1;31m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    v2ray stream
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    tls () {
    clear
    echo -e "\E[44;1;37m            Activar o desactivar TLS             \E[0m"
    v2ray tls
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    portv () {
    echo -e "\E[44;1;37m            CAMBIAR PUERTO V2RAY             \E[0m"
    v2ray port
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    stats () {
    echo -e "\E[44;1;37m            ESTADISTICAS DE CONSUMO             \E[0m"
    v2ray stats
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    unistallv2 () {
    source <(curl -sL https://multi.netlify.app/v2ray.sh) --remove > /dev/null 2>&1
    rm -rf /etc/SSHPlus/RegV2ray > /dev/null 2>&1
    echo -e "\n\033[1;32mV2RAY ELIMINADO CORRECTAMENTE.\033[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    infocuenta () {
    echo -e "\E[44;1;37m            INFORMACION DE CUENTA             \E[0m"
    v2ray info
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    addusr () {
    clear
    echo -e "\E[44;1;37m            AÑADIR USUARIO | UUID V2RAY             \E[0m"
    ##DIAS
    valid=$(date '+%C%y-%m-%d' -d " +31 days")		  
    ##CORREO		  
    MAILITO=$(cat /dev/urandom | tr -dc '[:alnum:]' | head -c 10)
    ##ADDUSERV2RAY		  
    UUID=`uuidgen`	  
    sed -i '13i\           \{' /etc/v2ray/config.json
    sed -i '14i\           \"alterId": 0,' /etc/v2ray/config.json
    sed -i '15i\           \"id": "'$UUID'",' /etc/v2ray/config.json
    sed -i '16i\           \"email": "'$MAILITO'@gmail.com"' /etc/v2ray/config.json
    sed -i '17i\           \},' /etc/v2ray/config.json
    echo ""
    while true; do
    echo -ne "\e[91m >> Escriba un nombre de usuario: \033[1;92m"
         read -p ": " nick
         nick="$(echo $nick|sed -e 's/[^a-z0-9 -]//ig')"
         if [[ -z $nick ]]; then
         echo -e "$msg17" && continue
         elif [[ "${#nick}" -lt "2" ]]; then
         echo -e "$msg02" && continue
         elif [[ "${#nick}" -gt "20" ]]; then
         echo -e "$msg03" && continue
         fi
         break
    done
    echo -e "\e[91m >> UUID generado: \e[92m$UUID "
    while true; do
         echo -ne "\e[91m >> Duracion del UUID (dias):\033[1;92m " && read diasuser
         if [[ -z "$diasuser" ]]; then
         echo -e "$msg17" && continue
         elif [[ "$diasuser" != +([0-9]) ]]; then
         echo -e "$msg08" && continue
         elif [[ "$diasuser" -gt "360" ]]; then
         echo -e "$msg09" && continue
         fi 
         break
    done
    #Lim
    [[ $(cat /etc/passwd |grep $1: |grep -vi [a-z]$1 |grep -v [0-9]$1 > /dev/null) ]] && return 1
    valid=$(date '+%C%y-%m-%d' -d " +$diasuser days") && datexp=$(date "+%F" -d " + $diasuser days")
    echo -e "\e[91m >> Expira el: \e[92m$datexp "
    ##Registro
    echo "  $UUID | $nick | $valid " >> /etc/SSHPlus/RegV2ray
    Fecha=`date +%d-%m-%y-%R`
    cp /etc/SSHPlus/RegV2ray /etc/SSHPlus/v2ray/RegV2ray-"$Fecha"
    v2ray restart > /dev/null 2>&1
    echo ""
    v2ray info > /etc/SSHPlus/v2ray/confuuid.log
    lineP=$(sed -n '/'${UUID}'/=' /etc/SSHPlus/v2ray/confuuid.log)
    numl1=4
    let suma=$lineP+$numl1
    sed -n ${suma}p /etc/SSHPlus/v2ray/confuuid.log 
    echo ""
    sed -i "11 s;104.16.18.94%3A443;$nick;g" /etc/SSHPlus/v2ray/confuuid.log
    cat /etc/SSHPlus/v2ray/confuuid.log  | sed -n '11 p'
    echo "" 
echo "APP ANDROID:"
echo "Descarga en el enlace"
echo "" 
echo "App: https://play.google.com/store/apps/details?id=com.v2ray.ang" 
echo "" 
echo "" 
echo "APP IPHONE:"
echo "Descarga en el enlace"
echo "" 
echo "App: https://apps.apple.com/br/app/fair-vpn/id1533873488" 
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\e[92m           UUID AGREGADO CORRECTAMENTE "
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }

    delusr () {
    clear 
    clear
    invaliduuid () {
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\e[91m                    UUID NO VALIDO \n"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;37m            ELIMINAR USUARIO | UUID V2RAY             \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\e[97m               USUARIOS REGISTRADOS"
    echo -e "\e[33m$(cat /etc/SSHPlus/RegV2ray|cut -d '|' -f2,1)" 
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -ne "\e[91m >> Escriba el UUID a eliminar:\n \033[1;92m " && read uuidel
    [[ $(sed -n '/'${uuidel}'/=' /etc/v2ray/config.json|head -1) ]] || invaliduuid
    lineP=$(sed -n '/'${uuidel}'/=' /etc/v2ray/config.json)
    linePre=$(sed -n '/'${uuidel}'/=' /etc/SSHPlus/RegV2ray)
    sed -i "${linePre}d" /etc/SSHPlus/RegV2ray
    numl1=2
    let resta=$lineP-$numl1
    sed -i "${resta}d" /etc/v2ray/config.json
    sed -i "${resta}d" /etc/v2ray/config.json
    sed -i "${resta}d" /etc/v2ray/config.json
    sed -i "${resta}d" /etc/v2ray/config.json
    sed -i "${resta}d" /etc/v2ray/config.json
    v2ray restart > /dev/null 2>&1
    echo ""
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\e[92m           UUID ELIMINADO CORRECTAMENTE "
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }

    mosusr_kk() {
    clear 
    clear
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;37m            USUARIOS REGISTRADOS | UUID V2RAY             \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    # usersss=$(cat /etc/SSHPlus/RegV2ray|cut -d '|' -f1)
    # cat /etc/SSHPlus/RegV2ray|cut -d'|' -f3
    VPSsec=$(date +%s)
    local HOST="/etc/SSHPlus/RegV2ray"
    local HOST2="/etc/SSHPlus/RegV2ray"
    local RETURN="$(cat $HOST|cut -d'|' -f2)"
    local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
    if [[ -z $RETURN ]]; then
    echo -e "----- NINGUN USUARIO REGISTRADO -----"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    else
    i=1
    echo -e "\e[97m                 UUID                | USER | EXPIRACION \e[93m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    while read hostreturn ; do
    DateExp="$(cat /etc/SSHPlus/RegV2ray|grep -w "$hostreturn"|cut -d'|' -f3)"
    if [[ ! -z $DateExp ]]; then             
    DataSec=$(date +%s --date="$DateExp")
    [[ "$VPSsec" -gt "$DataSec" ]] && EXPTIME="\e[91m[EXPIRADO]\e[97m" || EXPTIME="\e[92m[$(($(($DataSec - $VPSsec)) / 86400))]\e[97m Dias"
    else
    EXPTIME="\e[91m[ S/R ]"
    fi 
    usris="$(cat /etc/SSHPlus/RegV2ray|grep -w "$hostreturn"|cut -d'|' -f2)"
    local contador_secuencial+="\e[93m$hostreturn \e[97m|\e[93m$usris\e[97m|\e[93m $EXPTIME \n"           
          if [[ $i -gt 30 ]]; then
    	      echo -e "$contador_secuencial"
    	  unset contador_secuencial
    	  unset i
    	  fi
    let i++
    done <<< "$IDEUUID"
    [[ ! -z $contador_secuencial ]] && {
    linesss=$(cat /etc/SSHPlus/RegV2ray | wc -l)
    	      echo -e "$contador_secuencial \n Numero de registros: $linesss"
    	}
    fi
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    lim_port () {
    clear 
    clear
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;37m            LIMITAR MB x PUERTO | UUID V2RAY             \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    ###VER
    estarts () {
    VPSsec=$(date +%s)
    local HOST="/etc/SSHPlus/v2ray/lisportt.log"
    local HOST2="/etc/SSHPlus/v2ray/lisportt.log"
    local RETURN="$(cat $HOST|cut -d'|' -f2)"
    local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
    if [[ -z $RETURN ]]; then
    echo -e "----- NINGUN PUERTO REGISTRADO -----"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    else
    i=1
    while read hostreturn ; do
    iptables -n -v -L > /etc/SSHPlus/v2ray/data1.log 
    statsss=$(cat /etc/SSHPlus/v2ray/data1.log|grep -w "tcp spt:$hostreturn quota:"|cut -d' ' -f3,4,5)
    gblim=$(cat /etc/SSHPlus/v2ray/lisportt.log|grep -w "$hostreturn"|cut -d'|' -f2)
    local contador_secuencial+="         \e[97mPUERTO: \e[93m$hostreturn \e[97m|\e[93m$statsss \e[97m|\e[93m $gblim GB  \n"          
          if [[ $i -gt 30 ]]; then
    	      echo -e "$contador_secuencial"
    	  unset contador_secuencial
    	  unset i
    	  fi
    let i++
    done <<< "$IDEUUID"
    [[ ! -z $contador_secuencial ]] && {
    linesss=$(cat /etc/SSHPlus/v2ray/lisportt.log | wc -l)
    	      echo -e "$contador_secuencial \n Puertos Limitados: $linesss"
    	}
    fi
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager 
    }
    ###LIM
    liport () {
    while true; do
         echo -ne "\e[91m >> Puerto a limitar:\033[1;92m " && read portbg
         if [[ -z "$portbg" ]]; then
         echo -e "$msg17" && continue
         elif [[ "$portbg" != +([0-9]) ]]; then
         echo -e "$msg16" && continue
         elif [[ "$portbg" -gt "1000" ]]; then
         echo -e "$msg16" && continue
         fi 
         break
    done
    while true; do
         echo -ne "\e[91m >> Cantidad de GB:\033[1;92m " && read capgb
         if [[ -z "$capgb" ]]; then
         echo -e "$msg17" && continue
         elif [[ "$capgb" != +([0-9]) ]]; then
         echo -e "$msg15" && continue
         elif [[ "$capgb" -gt "1000" ]]; then
         echo -e "$msg15" && continue
         fi 
         break
    done
    uml1=1073741824
    gbuser="$capgb"
    let multiplicacion=$uml1*$gbuser
    sudo iptables -I OUTPUT -p tcp --sport $portbg -j DROP
    sudo iptables -I OUTPUT -p tcp --sport $portbg -m quota --quota $multiplicacion -j ACCEPT
    iptables-save > /etc/iptables/rules.v4
    echo ""
    echo -e " Puerto seleccionado: $portbg | Cantidad de GB: $gbuser"
    echo ""
    echo " $portbg | $gbuser | $multiplicacion " >> /etc/SSHPlus/v2ray/lisportt.log 
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    ###RES
    resdata () {
    VPSsec=$(date +%s)
    local HOST="/etc/SSHPlus/v2ray/lisportt.log"
    local HOST2="/etc/SSHPlus/v2ray/lisportt.log"
    local RETURN="$(cat $HOST|cut -d'|' -f2)"
    local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
    if [[ -z $RETURN ]]; then
    echo -e "----- NINGUN PUERTO REGISTRADO -----"
    return 0
    else
    i=1
    while read hostreturn ; do
    iptables -n -v -L > /etc/SSHPlus/v2ray/data1.log 
    statsss=$(cat /etc/SSHPlus/v2ray/data1.log|grep -w "tcp spt:$hostreturn quota:"|cut -d' ' -f3,4,5)
    gblim=$(cat /etc/SSHPlus/v2ray/lisportt.log|grep -w "$hostreturn"|cut -d'|' -f2)
    local contador_secuencial+="         \e[97mPUERTO: \e[93m$hostreturn \e[97m|\e[93m$statsss \e[97m|\e[93m $gblim GB  \n"  
            
          if [[ $i -gt 30 ]]; then
    	      echo -e "$contador_secuencial"
    	  unset contador_secuencial
    	  unset i
    	  fi
    let i++
    done <<< "$IDEUUID"

    [[ ! -z $contador_secuencial ]] && {
    linesss=$(cat /etc/SSHPlus/v2ray/lisportt.log | wc -l)
    	      echo -e "$contador_secuencial \n Puertos Limitados: $linesss"
    	}
    fi
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

    while true; do
         echo -ne "\e[91m >> Puerto a limpiar:\033[1;92m " && read portbg
         if [[ -z "$portbg" ]]; then
         echo -e "$msg17" && continue
         elif [[ "$portbg" != +([0-9]) ]]; then
         echo -e "$msg16" && continue
         elif [[ "$portbg" -gt "1000" ]]; then
         echo -e "$msg16" && continue
         fi 
         break
    done
    invaliduuid () {
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\e[91m                PUERTO NO VALIDO \n"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    [[ $(sed -n '/'${portbg}'/=' /etc/SSHPlus/v2ray/lisportt.log|head -1) ]] || invaliduuid
    gblim=$(cat /etc/SSHPlus/v2ray/lisportt.log|grep -w "$portbg"|cut -d'|' -f3)
    sudo iptables -D OUTPUT -p tcp --sport $portbg -j DROP
    sudo iptables -D OUTPUT -p tcp --sport $portbg -m quota --quota $gblim -j ACCEPT
    iptables-save > /etc/iptables/rules.v4
    lineP=$(sed -n '/'${portbg}'/=' /etc/SSHPlus/v2ray/lisportt.log)
    sed -i "${linePre}d" /etc/SSHPlus/v2ray/lisportt.log
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager
    }
    ## MENU
    echo -e "\033[1;37m\033[1;33m[1] > LIMITAR DATOS x PUERTO\033[1;31m"
    echo -e "\033[1;37m\033[1;33m[2] > RESTABLECER DATOS DE PUERTO\033[1;31m"
    echo -e "\033[1;37m\033[1;33m[3] > VER DATOS CONSUMIDOS\033[1;31m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;32m [0] > \e[97m\033[1;41m VOLVER \033[1;37m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    selection=$(selection_fun 3)
    case ${selection} in
    1)liport ;;
    2)resdata;;
    3)estarts;;
    0)
    fun_v2raymanager
    ;;
    esac
    }

    #.
    limpiador_activador () {
    unset PIDGEN
    PIDGEN=$(ps aux|grep -v grep|grep "limv2ray")
    if [[ ! $PIDGEN ]]; then
    screen -dmS limv2ray watch -n 21600 limv2ray
    else
    #killall screen
    screen -S limv2ray -p 0 -X quit
    fi
    unset PID_GEN
    PID_GEN=$(ps x|grep -v grep|grep "limv2ray")
    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESACTIVADO ] " || PID_GEN="\e[92m [ ACTIVADO ] "
    statgen="$(echo $PID_GEN)"
    clear 
    clear
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;37m            ELIMINAR EXPIRADOS | UUID V2RAY             \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo ""
    echo -e "                    $statgen " 
    echo "" 						
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;37m• \033[1;33mEnter para continuar\033[1;31m" && read enter
    fun_v2raymanager

    }

    selection_fun () {
    local selection="null"
    local range
    for((i=0; i<=$1; i++)); do range[$i]="$i "; done
    while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
    echo -ne "\033[1;37m ► Seleccione una opción: " >&2
    read selection
    tput cuu1 >&2 && tput dl1 >&2
    done
    echo $selection
    }

    PID_GEN=$(ps x|grep -v grep|grep "limv2ray")
    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESACTIVADO ] " || PID_GEN="\e[92m [ ACTIVADO ] "
    statgen="$(echo $PID_GEN)"
    #SPR & 
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

    fun_v2raymanager() {
		while true $x != "ok"; do
			[[ ! -e '/home/sshplus' ]] && exit 0
			clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%55s%s%-12s\n' "V2RAY PRO Dev. J DAVID AG " ; tput sgr0
echo "Para activar (V2RAY) es obligatorio que todos los demás modos de conexión estén (DESACTIVADOS)"
echo "" 
			xv2ray1=`if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
			echo -e "\e[92m ACTIVADO"
			else
			echo -e "\e[91m DESACTIVADO"
			fi`;
            echo -e "\033[1;32mSERVICIO: \033[1;33mV2RAY \033[1;32m$xv2ray1\033[1;37m" 
			xv2ray=`if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
			echo -e "\033[1;32m◉ "
			else
			echo -e "\033[1;31m○ "
			fi`;          
			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
			echo ""
echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mCREAR USUARIO V2RAY\033[1;31m
[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mELIMINAR USUARIO\033[1;31m
[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mMOSTRAR USUARIOS REGISTRADOS\033[1;31m
[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mINFORMACION DE CONEXION\033[1;31m
[\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mESTADISTICAS DE CONSUMO\033[1;31m
[\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mLIMITAR USUARIO POR CONSUMO\e[91m\033[1;31m
[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mELIMINAR VENCIDOS $statgen\033[1;31m
[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCAMBIAR PROTOCOLO\033[1;31m
[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mACTIVAR TLS\033[1;31m
[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mCAMBIAR PUERTO V2RAY\033[1;31m 
[\033[1;36m11\033[1;31m] \033[1;37m• \033[1;33mINSTALAR V2RAY $xv2ray\033[1;31m
[\033[1;36m12\033[1;31m] \033[1;37m• \033[1;33mDESINSTALAR V2RAY\033[1;31m
[\033[1;36m13\033[1;31m] \033[1;37m• \033[1;33mVOLVER \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m"

			echo ""
			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
			echo ""
			tput civis
			echo -ne "\033[1;32mQUÉ DESEA HACER \033[1;33m?\033[1;31m?\033[1;37m "
			read x
			tput cnorm
			clear
			case $x in
			11)
				intallv2ray
				;;
			8 | 08)
				protocolv2ray
				;;
			9 | 09)
				tls
				;;
			10 | 10)
				portv
				;;
			1 | 01)
				addusr
				;;
			2 | 02)
				delusr
				;;
			3 | 03)
				mosusr_kk
				;;
		    4 | 04)
				infocuenta
                ;;              
		    5 | 05)
				stats
				;;
		    6 | 06)
				lim_port
				;;                
			7 | 07)
				limpiador_activador
				;;
            12 | 12)
				unistallv2
				;;
            13 | 13)
				conexao
                exit;
				;;

			0 | 00)
				echo -e "\033[1;31mVolviendo al menu...\033[0m"
				sleep 2
				clear
				menu
				;;
			*)
				echo -e "\033[1;31mOpcion no valida!\033[0m"
				sleep 2
				;;
			esac
		done
	}
    fun_v2raymanager

}
